//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Biblio_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adherant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adherant()
        {
            this.Livres = new HashSet<Livre>();
        }
    
        public int Id { get; set; }
        public string addresse { get; set; }
        public int anciennete { get; set; }
        public System.DateTime date_entre { get; set; }
        public string nom { get; set; }
        public string sexe { get; set; }
        public int age { get; set; }
        public string tel { get; set; }
        public string password { get; set; }
        public int Bibliothequaire_Id { get; set; }
    
        public virtual Bibliothequaire Bibliothequaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Livre> Livres { get; set; }
    }
}
