//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Biblio_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directeur
    {
        public int Id { get; set; }
        public string password { get; set; }
        public string nom { get; set; }
        public string sexe { get; set; }
        public int age { get; set; }
        public string tel { get; set; }
    }
}
